### ISSUE TITLE
HCConanSword showing error in loading

### ISSUE THREAD

**Issue by MurphysLaw26** [robotex140/Hydrocraft#10]
Describe the bug
I loaded just the current Hydrocraft build, and looked into the debug log. Saw the following errorr

[20-03-22 16:41:34.694] LOG  : General     , 1647808894694> java.security.InvalidParameterException: Error: --updated is not a valid parameter in item: HCConanSword.

investigating HCConanSword, and looking at "media\scripts\Weapon Blades.txt"

	item HCConanSword	
	{
		DisplayName					=	Conan Sword,

...

		MinAngle					=	0.2,
		TwoHandWeapon 				= 	TRUE,
		BreakSound  				=   KatanaBreak, --updated, copied from Base.Katana
		TreeDamage  				=   10,
		AttachmentType 				= 	BigBlade,
		DisplayCategory				=	Weapon,  --new, copied from Base.Katana
		BaseSpeed					=	1,  --new, copied from Base.Katana
		WeaponLength				=	0.4,  --new, copied from Base.Katana
		DamageCategory				=	Slash,  --new, copied from Base.Katana
		DamageMakeHole				=	TRUE,  --new, copied from Base.Katana
		CritDmgMultiplier			=	6,  --new, copied from Base.Katana

I suspect the comments put after the arguments are being taken as part of the argument, which would explain the errors

To Reproduce

Remove all saves
Load Hydrocraft B41 continued only
Close game and reopen
review Debuglog
Expected behavior

I believe the model should load without error

**Comment by HugoQwerty** [comment]
Ah yes, this was my fault.  I fixed it a few days ago - it should be in the latest Steam release already.
