### ISSUE TITLE
HCPlankTreated showing error during load

### ISSUE THREAD

**Issue by MurphysLaw26** [robotex140/Hydrocraft#11]
Describe the bug
I loaded just the current Hydrocraft build, and looked into the debug log. Saw the following errorr

[20-03-22 21:51:50.406] WARN : Script      , 1647827510406> ModelScript.check> no such model "WoodPlank" for Hydrocraft.HCPlanktreated.

investigating HCPlanktreated, and looking at "media\scripts\Firecrafting.txt"

item HCPlanktreated
	{
		MaxRange			=	2,
		WeaponSprite			=	WoodPlank,
		MinAngle			=	0.2,
		Type				=	Weapon,

I suspect that they wanted the default Plank Sprite from the base game, and looking at the base game /media/scriipts/items_weapons.txt

    item Plank
	{
	    DisplayCategory = Material,
		MaxRange	=	1.3,
		WeaponSprite	=	Plank,

I suspect WeaponSprite for HCPlanktreated needs to be changed to Plank

To Reproduce

Remove all saves
Load Hydrocraft B41 continued only
Close game and reopen
review Debuglog
Expected behavior

I believe the model should load without error

**Comment by HugoQwerty** [comment]
Done.  Also set it to 2-handed like the standard plank.
