### ISSUE TITLE
HCSleep.lua unable to load Camping/camping - not sure if it is needed.

### ISSUE THREAD

**Issue by MurphysLaw26** [robotex140/Hydrocraft#12]
**Describe the bug**
[20-03-22 21:51:55.260] LOG  : Lua         , 1647827515260> Loading: C:/Program Files (x86)/Steam/steamapps/workshop/content/108600/2778991696/mods/Hydrocraft/media/lua/client/Sleep/HCSleep.lua.
[20-03-22 21:51:55.261] WARN : Lua         , 1647827515261> LuaManager$GlobalObject.require> require("Camping/camping") failed.

I am less certain about this whether this is actually an issue - looking into /media/lua/HCSleep.lua, it looks to load two dependencies

HCRestKey = HCSleepKey; --"restin"; 

require 'Camping/camping'
require "TimedActions/ISBaseTimedAction"
HCSleep = {};

Now, /media/lua/client/Camping does not exist in Hydrocraft, but it does look to exist in Base. There are two directories in there - ISUI and TimedActions. TimedActions in Base does NOT contain ISBasedTimedAction, so I suspect that the "require 'Camping/camping' can be removed from HCSleep, as it is no longer needed

Remove all saves
Load Hydrocraft B41 continued only
Close game and reopen
review Debuglog
Expected behavior

I believe the HCSleep.lua should function without the Camping/camping dependancy

**Comment by HugoQwerty** [comment]
Done.
