### ISSUE TITLE
Use broken glass like glass shards to recycle glass

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#20]
**Is your feature request related to a problem? Please describe.**
There is broken glass in the game and as far as I can tell there is no current use for it.

**Describe the solution you'd like**
Like this maybe?
https://github.com/robotex140/Hydrocraft/blob/main/Contents/mods/Hydrocraft/media/scripts/Recycling%20Glass.txt
```
recipe Recycle Glass
    {
    Moveables.brokenglass_1_1=20/Moveables.brokenglass_1_2=20,
    Charcoal,
    Lighter/Matches/PercedWood/HCMagnesiumstriker/HCBowdrill,
    HCIngotmold=1,
    keep Tongs,
    keep HCWorkgloves/HCGlovesHardLeather/HCFiresuit,
    keep HCSmelter2/HCFurnace2/HCBlastfurnace2,
    CanBeDoneFromFloor:true,
    Result:HCGlassingot=1,
    NeedToBeLearn:true,
    Time:1000,
    Category:Glassworking,
    OnCreate:getBurned,
    OnGiveXP:HCWelding_OnGiveXP,
    }
```

**Describe alternatives you've considered**
-

**Additional context**
I have searched for the item id for the broken glass but was not able to get it.
https://pzwiki.net/wiki/Broken_Glass

**Comment by lanceris** [comment]
\<PlaceholderForBrokenglassID\> would be `Moveables.brokenglass_1_1` or `Moveables.brokenglass_1_2` (from [Viperel's Recycling Center](https://steamcommunity.com/sharedfiles/filedetails/?id=2713055926) mod)

**Comment by axi92** [comment]
Ty @lanceris I updated the recipe. I hope it is syntax correct.

**Comment by Yell420** [comment]
seems like a great addition, however the amount is too large i would say consdering you can grab a window from a car and smelt that. somewhere along the lines of 2-5 broken glass per ingot would be more reasonable

Can push this with my pull request #31  if @robotex140 / @HugoQwerty agree
