### ISSUE TITLE
Edit vanilla recipes?

### ISSUE THREAD

**Issue by HugoQwerty** [robotex140/Hydrocraft#25]
So, I was trying to disable some vanilla recipes to get rid of the 'butcher' recipes and replace them with my own.  The only way I found was to replace /media/scripts/recipe.txt (vanilla) by creating our own in HC - the original is then ignored.  [I don't know what happens if two mods do this].

Anyway, with this we could remove / edit any recipe we want.

We could add a risk of injury to clumsy / unlucky characters, we could add additional requirement (e.g. can't do x when tired), we can merge some together (all the dismantle electronics are there own recipe, as are the open sack of food recipes), we could vary the result based on skills / profession (e.g. less planks at low carpentry), we can add new tools to a recipe, like HC knives to vanilla recipes.

The rather large downside, is that we would need to re-copy the vanilla file after every update to make sure any changes aren't missing from HC, and then meticulously make our bespoke changes.  Maybe a script could be written to automate this?

**Comment by FenrirZeroZero** [comment]
Can't you just overwrite the old recipes? Or do they also have the issue with all being called with the same name?

**Comment by HugoQwerty** [comment]
I couldn't figure out how to do that, without copying the whole file.  I've read you can mark them Override: true, Obsolete: true - but if I didn't copy the whole file every other recipe in the game ceased to exist.  If I just add new recipes then they both appear.

I did have one other option, use lua to mark them as needing to be learned - so I might do that, but that wouldn't let us do whatever we want with vanilla recipes, which I think could be interesting.

**Comment by FenrirZeroZero** [comment]
This should work. 
You need to be in module base to overwrite recipes of the base game

module Base
{
    recipe Butcher Small Animal
    {
        keep KitchenKnife/HuntingKnife/MeatCleaver/FlintKnife/Machete,
        DeadMouse/DeadSquirrel/DeadRat,

        Result:Smallanimalmeat,
        Sound:PZ_FoodSwoosh,
        Time:50.0,
        OnCreate:Recipe.OnCreate.CutAnimal,
        Category:Cooking,
        OnGiveXP:Recipe.OnGiveXP.Cooking10,
Override: true, 
Obsolete: true,
    }

    recipe Butcher Rabbit
    {
        keep KitchenKnife/HuntingKnife/MeatCleaver/FlintKnife/Machete,
        DeadRabbit,

        Result:Rabbitmeat,
        Sound:PZ_FoodSwoosh,
        Time:50.0,
        OnCreate:Recipe.OnCreate.CutAnimal,
        Category:Cooking,
        OnGiveXP:Recipe.OnGiveXP.Cooking10,
Override: true, 
Obsolete: true,
    }

    recipe Butcher Bird
    {
        keep KitchenKnife/HuntingKnife/MeatCleaver/FlintKnife/Machete,
        DeadBird,

        Result:Smallbirdmeat,
        Sound:PZ_FoodSwoosh,
        Time:50.0,
        OnCreate:Recipe.OnCreate.CutAnimal,
        Category:Cooking,
        OnGiveXP:Recipe.OnGiveXP.Cooking10,
Override: true, 
Obsolete: true,
    }
}

**Comment by HugoQwerty** [comment]
Thanks.  I'll try again, but I think I did that - it didn't work unless I called the file recipes.txt, and when I did that all the other vanilla recipes disappeared as well.

**Comment by FenrirZeroZero** [comment]
You can look into the "Carpentry" Script File there i am overwriting some Base recipes.
Only issue i had was wenn i tried overwriting a recipes that had the same name multiple times. (Unstack in example)

**Comment by HugoQwerty** [comment]
Thanks, I'll try and look into it later - currently working on what should be a nice surprise.

**Comment by HugoQwerty** [comment]
I've managed to override recipes, but hiding vanilla recipes just doesn't seem to work.

**Comment by HugoQwerty** [comment]
module Base
{
    recipe Butcher Rabbit
    {
        Result:Nothing_Small_Meat,
	RemoveResultItem:true,
        Sound:PZ_FoodSwoosh,
        Time:50.0,
        Category:Cooking,
	Override: true,
	IsHidden: true,
    }
}

Hidden on the crafting menu, it would apparently still appear on the right-click menu - but as it has no ingredients, it should never appear there either.
