### ISSUE TITLE
Bug in Cats.txt

### ISSUE THREAD

**Issue by lanceris** [robotex140/Hydrocraft#35]
While working on Craft Helper stuff, I've found an error in this script (second to last entry)

https://github.com/robotex140/Hydrocraft/blob/466da3a87ecd060bbf62bd58e18af0bb0f69ef13/Contents/mods/Hydrocraft/media/scripts/Cats.txt#L251

I think possible fix is to change `Hydrocraft.HCCatwhitemale` to `HCCatwhitemale`

**Comment by Yell420** [comment]
this seems to be a bigger issue.... HCCatwhitemale exists in Cats.txt but does not appear to be an item that can be spawned.. it doesnt exist for some reason.
![image](https://user-images.githubusercontent.com/102168061/162592416-7ff929f3-75db-4f65-aa7f-027d1b55acf8.png)

**Comment by Yell420** [comment]
![image](https://user-images.githubusercontent.com/102168061/162592663-2d16cdc3-13e6-4968-a73e-159e165a2401.png)

to give devs an idea, this is what the actual name appears to be, i havnt figured out how to correct it yet.

**Comment by HugoQwerty** [comment]
Weird, maybe try deleting the HCCatwhilemale entry in cats.txt and seeing if HCCatwhale disappears too?

**Comment by lanceris** [comment]
Seems like `item` got removed from HCCatWh**item**ale during parsing, try to rename to smth without `item` in name

**Comment by lanceris** [comment]
Lol yeah, thats the case
![image](https://user-images.githubusercontent.com/17213746/162593991-03882e8c-27aa-47b0-944a-27ea733762ae.png)

**Comment by lanceris** [comment]
Some goes for all other blocks (recipe, fixing etc)
