### ISSUE TITLE
Bug in "Weapons Bats.txt"

### ISSUE THREAD

**Issue by lanceris** [robotex140/Hydrocraft#36]
`Base.TentPeg` in this file should be replaced with `camping.TentPeg` to work properly
https://github.com/robotex140/Hydrocraft/blob/466da3a87ecd060bbf62bd58e18af0bb0f69ef13/Contents/mods/Hydrocraft/media/scripts/Weapons%20Bats.txt#L1832

![image](https://user-images.githubusercontent.com/17213746/162590550-96626d5c-6bb5-43c3-8b8b-cdd46e3da54b.png)

**Comment by Yell420** [comment]
Nice find, i pushed a commit for the devs with my recent changes and your bug find
