### ISSUE TITLE
2x recipe Make Computer Tower

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#43]
**Describe the bug**
The recipe exists 2 times, the only difference is the craft time, is that supposed to be like that?

**To Reproduce**
1. https://github.com/robotex140/Hydrocraft/blob/28ce89066f123c79cb19c1ff2da5ca7521ac02bf/Contents/mods/Hydrocraft/media/scripts/Electronics.txt#L1573
2. https://github.com/robotex140/Hydrocraft/blob/28ce89066f123c79cb19c1ff2da5ca7521ac02bf/Contents/mods/Hydrocraft/media/scripts/Electronics.txt#L1607

**Expected behavior**
Only one recipe

**Screenshots**

**Additional context**

**Comment by Yell420** [comment]
Based on the other recipes.. this one with the longer time should not have the bench as a requirement.

**Comment by Yell420** [comment]
Based on the other recipes.. this one with the longer time should not have the bench as a requirement.
