### ISSUE TITLE
Book Cover as burning fuel

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#52]
**Is your feature request related to a problem? Please describe.**
As Book Covers are right now "Useless" we could use them as burning fuel.

**Describe the solution you'd like**
Burning fuel category.

**Describe alternatives you've considered**

**Additional context**
![grafik](https://user-images.githubusercontent.com/1394837/166061753-5f66ab24-56f8-49c7-a592-dc33e3402025.png)

**Comment by HugoQwerty** [comment]
Sure.

Note to self: /media/lua/server/camping/HCCamping_fuel.lua

Fuel & Starter.

**Comment by HugoQwerty** [comment]
Done.
