### ISSUE TITLE
HCMagpiedead missing icon

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#61]
![grafik](https://user-images.githubusercontent.com/1394837/167314630-029875d8-35e4-4361-9cd3-b999add8c70f.png)

**Comment by HugoQwerty** [comment]
Fixed.

For info, here was the issue:

item HCMagpiedead
	{
	Weight 				= 	0.2,
	Type				=	Food,
	DangerousUncooked	=	TRUE,
	DaysTotallyRotten	=	4,
	DaysFresh			=	2,
	FoodType			=	Game,
	DisplayName			= 	Dead Magpie,
	Icon				=	HCMagpiedead    <-------------- missing a comma
	DisplayCategory		=	AnimalDead,
	}
