### ISSUE TITLE
HCBookplastics does not have recipes

### ISSUE THREAD

**Issue by axi92** [robotex140/Hydrocraft#62]
This book does not have TeachedRecipes, is this intended?

https://github.com/robotex140/Hydrocraft/blob/0fc9b7e95c76ec2d2213cc8df5700f5ed31374c1/Contents/mods/Hydrocraft/media/scripts/Books.txt#L1829-L1837

**Comment by HugoQwerty** [comment]
No idea, but if it has no use we can probably remove it.  I'd also be in favour of removing all the useless books (or coming up with a use for them).  Even the -5 stress books seem like they could go - we really don't need more way of reducing stress etc.

**Comment by robotex140** [comment]
Agreed. I can't think of plastic usage immediately so when I get home I'll just comment it out, might as well keep the item in the code if in future we want to do stuff with plastic

**Comment by HugoQwerty** [comment]
Book removed.
