### ISSUE TITLE
HCDobermanfemalewar error on loading

### ISSUE THREAD

**Issue by MurphysLaw26** [robotex140/Hydrocraft#9]
Describe the bug
I loaded just the current Hydrocraft build, and looked into the debug log. Saw the following errorr

[20-03-22 15:58:06.131] WARN : Script , 1647806286131> ModelScript.check> no such model "Dog" for Hydrocraft.HCDobermanfemalewar.

investigating HCDobermanfemalewar, and looking at "media\scripts\Dogs.txt"

item HCDobermanmalewarSpiked ***working***
	{
		MaxRange				=	17,
		WeaponSprite			=	Hydrocraft.HCWardog,

item HCDobermanfemalewar
	{
		MaxRange				=	15,
		WeaponSprite			=	Dog,

I suspect WeaponSprite for HCDobermanfemalewar needs to be changed to Hydrocraft.HCWardog

**To Reproduce**
1. Remove all saves
2. Load Hydrocraft B41 continued only
3. Close game and reopen
4. review Debuglog

Expected behavior

I believe the model should load without error

**Comment by HugoQwerty** [comment]
Done.
